[phases.setup]
nixPkgs = ["nodejs_20", "npm"]

[phases.build]
cmds = [
  "cd frontend/backend && npm install",
  "cd frontend && npm install",
  "cd frontend/backend && npm run build-frontend"
]

[phases.start]
cmd = "cd frontend/backend && node server.js"

[variables]
NODE_ENV = "production"
